#ifndef ESP_EZ_WIFI_CONSTANTS_H
#define ESP_EZ_WIFI_CONSTANTS_H

#define MIN_WIFI_SSID_LENGTH 2
#define MAX_WIFI_SSID_LENGTH 31
#define MIN_WIFI_PASSWORD_LENGTH 8
#define MAX_WIFI_PASSWORD_LENGTH 63

#endif